#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

feh --bg-fill $HOME/.specs/lain/wallpaper.png &
eww open bar &

hc keyunbind --all

# keybindings
Mod=Mod4
Alt=Mod1

# core
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close

# apps
hc keybind $Mod-Return spawn "alacritty"
hc keybind $Mod-Shift-Return spawn "alacritty" --class "alacritty-float"

hc keybind $Mod-d spawn "dmenu_run_apps"
hc keybind $Mod-e spawn "dmenu_emoji_menu"

# moving focus
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove

hc keybind $Mod-s floating  toggle
hc keybind $Mod-f fullscreen toggle

hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle

hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m        jumpto last-minimized

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c           cycle
hc keybind $Mod-i           jumpto urgent

# borders
hc attr theme.border_width          2
hc attr theme.outer_width           40
hc attr theme.active.outer_color    '#d17288'
hc attr theme.normal.outer_color    '#bc667a'

# title
hc attr theme.title_font    'Mononoki Nerd Font Mono:size=10'
hc attr theme.title_color   '#f5e3bb'
hc attr theme.title_align   center
hc attr theme.title_when    always
hc attr theme.title_height  24
hc attr theme.title_depth   14

# settings
hc set window_gap           12
hc set frame_border_width   0
hc set frame_gap            0
hc set focus_follows_mouse  1

# rules
hc unrule -F

hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

hc rule class~"(alacritty-float)" focus=on floating=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule fixedsize floating=on

hc set layout grid
hc set tree_style '╾│ ├└╼─┐'

hc unlock

# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
